import { useMemo, useRef, useState } from 'react';
import { Box, Button, Card, Chip, InputAdornment, TextField, Typography } from '@mui/material';
import { DashboardMain, SearchIcon, type SearchIconHandle } from '@stackbuild/ui';
import type { IngredientBranch } from '../../components/sidebar/IngredientBranchesSidebar';

type RequestStatus = 'รออนุมัติ' | 'กำลังจัดเตรียม' | 'จัดเสร็จแล้ว';
type SupplyType = 'วัตถุดิบ' | 'สต๊อก';
type SupplyItem = { name: string; quantity: string };
type SupplyRequest = { id: string; branch: Exclude<IngredientBranch, 'ทุกสาขา'>; type: SupplyType; items: SupplyItem[]; requestedAt: string; status: RequestStatus };
const requests: SupplyRequest[] = [
  { id: 'REQ-2048', branch: 'สยามสแควร์', type: 'วัตถุดิบ', items: [{ name: 'เมล็ดกาแฟ House Blend', quantity: '18 กก.' }, { name: 'นมสด', quantity: '30 ลิตร' }, { name: 'ไซรัปวานิลลา', quantity: '10 ขวด' }], requestedAt: 'วันนี้ 10:24', status: 'รออนุมัติ' },
  { id: 'REQ-2047', branch: 'อโศก', type: 'สต๊อก', items: [{ name: 'แก้วกระดาษ 16 oz', quantity: '400 ใบ' }, { name: 'ฝาแก้วร้อน', quantity: '200 ชิ้น' }, { name: 'หลอดกระดาษ', quantity: '180 ชิ้น' }], requestedAt: 'วันนี้ 09:40', status: 'กำลังจัดเตรียม' },
  { id: 'REQ-2046', branch: 'อารีย์', type: 'วัตถุดิบ', items: [{ name: 'ผงมัทฉะ', quantity: '5 กก.' }, { name: 'ผงโกโก้', quantity: '7 กก.' }], requestedAt: 'วันนี้ 08:15', status: 'จัดเสร็จแล้ว' },
  { id: 'REQ-2045', branch: 'ทองหล่อ', type: 'สต๊อก', items: [{ name: 'กล่องพัสดุ M', quantity: '80 กล่อง' }, { name: 'ถุงกระดาษหูหิ้ว', quantity: '100 ใบ' }], requestedAt: 'เมื่อวาน 17:32', status: 'จัดเสร็จแล้ว' },
  { id: 'REQ-2044', branch: 'เซ็นทรัลลาดพร้าว', type: 'วัตถุดิบ', items: [{ name: 'นมโอ๊ต', quantity: '16 ลิตร' }, { name: 'ซอสคาราเมล', quantity: '10 ขวด' }], requestedAt: 'เมื่อวาน 15:10', status: 'รออนุมัติ' },
  { id: 'REQ-2043', branch: 'สามย่าน', type: 'สต๊อก', items: [{ name: 'สติกเกอร์โลโก้', quantity: '240 แผ่น' }, { name: 'ทิชชู', quantity: '120 ห่อ' }], requestedAt: 'เมื่อวาน 11:05', status: 'กำลังจัดเตรียม' },
];
const statuses = ['ทั้งหมด', 'รออนุมัติ', 'กำลังจัดเตรียม', 'จัดเสร็จแล้ว'] as const;
const statusColors: Record<RequestStatus, { main: string; text: string }> = { 'รออนุมัติ': { main: '#805637', text: '#fff' }, 'กำลังจัดเตรียม': { main: '#ca7a16', text: '#fff' }, 'จัดเสร็จแล้ว': { main: '#e8eee9', text: '#3c5b47' } };
const nextStatus: Record<Exclude<RequestStatus, 'จัดเสร็จแล้ว'>, RequestStatus> = { 'รออนุมัติ': 'กำลังจัดเตรียม', 'กำลังจัดเตรียม': 'จัดเสร็จแล้ว' };
const actionLabel: Record<Exclude<RequestStatus, 'จัดเสร็จแล้ว'>, string> = { 'รออนุมัติ': 'อนุมัติคำขอ', 'กำลังจัดเตรียม': 'ยืนยันจัดเสร็จ' };

export function AdminOrdersPage({ activeBranch }: { activeBranch: IngredientBranch }) {
  const searchRef = useRef<SearchIconHandle>(null);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState<(typeof statuses)[number]>('ทั้งหมด');
  const [supplyType, setSupplyType] = useState<'ทั้งหมด' | SupplyType>('ทั้งหมด');
  const [requestStates, setRequestStates] = useState(requests);
  const filteredRequests = useMemo(() => requestStates.filter((request) => {
    const matchesBranch = activeBranch === 'ทุกสาขา' || request.branch === activeBranch;
    const matchesStatus = filter === 'ทั้งหมด' || request.status === filter;
    const matchesType = supplyType === 'ทั้งหมด' || request.type === supplyType;
    return matchesBranch && matchesStatus && matchesType && `${request.id}${request.branch}${request.items.map((item) => item.name).join(' ')}`.toLowerCase().includes(query.toLowerCase());
  }), [activeBranch, filter, query, requestStates, supplyType]);
  const advanceRequest = (id: string) => setRequestStates((current) => current.map((request) => request.id === id && request.status !== 'จัดเสร็จแล้ว' ? { ...request, status: nextStatus[request.status] } : request));
  const pendingCount = requestStates.filter((request) => request.status === 'รออนุมัติ' && (activeBranch === 'ทุกสาขา' || request.branch === activeBranch)).length;

  return <DashboardMain>
    <Box sx={{ display: 'flex', flexDirection: { xs: 'column', lg: 'row' }, justifyContent: 'space-between', alignItems: { lg: 'center' }, gap: 1.5, mb: 2 }}><Box><Typography sx={{ color: '#3c2d24', fontFamily: 'Kanit, sans-serif', fontSize: 20, fontWeight: 600 }}>คำขอเติมวัตถุดิบและสต๊อก</Typography><Typography sx={{ color: 'text.secondary', fontFamily: 'Kanit, sans-serif', fontSize: 13 }}>จัดการรายการที่แต่ละสาขาส่งขอมาเพื่อเติมสินค้า</Typography></Box><TextField value={query} onChange={(event) => setQuery(event.target.value)} onFocus={() => searchRef.current?.startAnimation()} onBlur={() => searchRef.current?.stopAnimation()} placeholder="ค้นหาเลขคำขอ สาขา หรือรายการ" size="small" sx={{ width: { xs: '100%', lg: 310 }, '& .MuiOutlinedInput-root': { borderRadius: '12px' } }} slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchIcon ref={searchRef} size={18} /></InputAdornment> } }} /></Box>
    <Card variant="outlined" sx={{ mb: 2, borderRadius: '15px', borderColor: '#e8ddd5', bgcolor: '#fffaf7' }}><Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, justifyContent: 'space-between', alignItems: { sm: 'center' }, gap: 1, p: 1.75 }}><Box><Typography sx={{ fontFamily: 'Kanit, sans-serif', fontSize: 14, fontWeight: 600 }}>{activeBranch === 'ทุกสาขา' ? 'ทุกสาขา' : `สาขา ${activeBranch}`}</Typography><Typography sx={{ color: 'text.secondary', fontFamily: 'Kanit, sans-serif', fontSize: 12 }}>มีคำขอรอการอนุมัติ {pendingCount} รายการ</Typography></Box><Box sx={{ display: 'flex', gap: .75 }}>{(['ทั้งหมด', 'วัตถุดิบ', 'สต๊อก'] as const).map((item) => <Button key={item} onClick={() => setSupplyType(item)} size="small" variant={supplyType === item ? 'contained' : 'outlined'} sx={{ minHeight: 32, borderRadius: '10px', borderColor: '#d8c8bd', bgcolor: supplyType === item ? '#201914' : '#fff', color: supplyType === item ? '#fff' : '#5f4b3d', fontFamily: 'Kanit, sans-serif', fontSize: 12, boxShadow: 'none' }}>{item}</Button>)}</Box></Box></Card>
    <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1, mb: 2 }}>{statuses.map((item) => <Button key={item} onClick={() => setFilter(item)} size="small" variant={filter === item ? 'contained' : 'outlined'} sx={{ minHeight: 34, borderRadius: '12px', borderColor: '#d8c8bd', bgcolor: filter === item ? '#201914' : '#fff', color: filter === item ? '#fff' : '#5f4b3d', fontFamily: 'Kanit, sans-serif', fontSize: 12, boxShadow: 'none' }}>{item}</Button>)}</Box>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, minmax(0, 1fr))', xl: 'repeat(3, minmax(0, 1fr))' }, gap: '16px' }}>{filteredRequests.map((request) => { const color = statusColors[request.status]; return <Card key={request.id} variant="outlined" sx={{ borderRadius: '15px', borderColor: '#e8ddd5' }}><Box sx={{ p: 2.5 }}><Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 1 }}><Box><Typography sx={{ color: '#3c2d24', fontFamily: 'Kanit, sans-serif', fontSize: 19, fontWeight: 600 }}>สาขา {request.branch}</Typography><Typography sx={{ mt: .15, color: 'text.secondary', fontFamily: 'Kanit, sans-serif', fontSize: 12 }}>{request.id}</Typography></Box><Chip label={request.status} size="small" sx={{ height: 25, borderRadius: '12px', bgcolor: color.main, color: color.text, fontFamily: 'Kanit, sans-serif', fontSize: 11 }} /></Box><Chip label={request.type} size="small" variant="outlined" sx={{ mt: 1.5, height: 24, borderRadius: '9px', borderColor: request.type === 'วัตถุดิบ' ? '#b8a296' : '#a8b6c1', color: request.type === 'วัตถุดิบ' ? '#805637' : '#276a9c', fontFamily: 'Kanit, sans-serif', fontSize: 11 }} /><Box sx={{ mt: 1.5, p: 1.25, borderRadius: '10px', bgcolor: '#f8f0eb', border: '1px solid #eadbd2' }}><Typography sx={{ mb: .75, color: '#5f4030', fontFamily: 'Kanit, sans-serif', fontSize: 13, fontWeight: 600 }}>รายการที่ขอ <Box component="span" sx={{ color: '#8a6b58', fontWeight: 500 }}>· {request.items.length} รายการ</Box></Typography>{request.items.map((item) => <Box key={item.name} sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 1, py: .5, '& + &': { borderTop: '1px solid #eadbd2' } }}><Typography sx={{ fontFamily: 'Kanit, sans-serif', fontSize: 13, fontWeight: 500 }}>{item.name}</Typography><Typography sx={{ flexShrink: 0, color: '#805637', fontFamily: 'Kanit, sans-serif', fontSize: 13, fontWeight: 600 }}>{item.quantity}</Typography></Box>)}</Box><Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 1, mt: 2 }}><Typography sx={{ color: 'text.secondary', fontFamily: 'Kanit, sans-serif', fontSize: 12 }}>{request.requestedAt}</Typography>{request.status !== 'จัดเสร็จแล้ว' && <Button onClick={() => advanceRequest(request.id)} variant="contained" size="small" sx={{ minHeight: 34, borderRadius: '10px', bgcolor: '#201914', fontFamily: 'Kanit, sans-serif', fontSize: 12, boxShadow: 'none', '&:hover': { bgcolor: '#3c2d24', boxShadow: 'none' } }}>{actionLabel[request.status]}</Button>}</Box></Box></Card>; })}</Box>
    {filteredRequests.length === 0 && <Typography sx={{ pt: 4, textAlign: 'center', color: 'text.secondary', fontFamily: 'Kanit, sans-serif' }}>ไม่พบคำขอที่ค้นหา</Typography>}
  </DashboardMain>;
}
